### ISSUE TITLE
Card Flip Functionality

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/sith_ly_the_best#5]
EPIC: Game functionality

As a **player** I can **click on a card to flip it over** so that ** I can reveal the image underneath.**

**Acceptance Criteria**
- [x] When clicking on a card it flips over and the user can see which card it is, after a period of time it will flip back over to its original state

**Tasks**
- [x] Create the JavaScript functionality for flipping over a selected card
- [x] Add the timing functionality to the cards
- [x] Check that per move the user can only flip over 2 cards at a time
- [x] If the cards selected are incorrect then they both flip back to their original state
- [x] Validate the JavaScript for this functionality
