### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/sith_ly_the_best#6]
EPIC: Landing Page

As a **user** I can **arrive on a home page with a short introduction and instructions** so that **I can understand how the game works.**

**Acceptance Criteria**
- [ ] A landing page with an introductory message, instructions as well as a button to start the game is visible to the user on arrival to our site.  

**Tasks**
- [ ] Create a Home page design (Wireframe)
- [ ] Add style to the Home page
- [ ] Add a Title (Name) to the page
- [ ] Add an intro to the page
- [ ] Add the rules of the game to the page
- [ ] Add a button to the page that starts the game
